apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: external-dns
    repo: https://charts.bitnami.com/bitnami
    version: 6.32.0
    valuesFile: values.yaml
    releaseName: external-dns
    namespace: externaldns