apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - Namespace.yaml

helmCharts:
- name: jupyterhub
  repo: https://hub.jupyter.org/helm-chart/
  version: 4.1.0  # Update to your desired version
  releaseName: jupyterhub
