apiVersion: batch/v1
kind: Job
metadata:
  name: patch-hub-rolebinding
  namespace: jupyterhub
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      serviceAccountName: jupyterhub-admin
      containers:
      - name: kubectl
        image: bitnami/kubectl:latest
        command:
          - /bin/sh
          - -c
          - |
            kubectl -n jupyterhub patch rolebinding hub --type=json -p='[{"op": "replace", "path": "/subjects/0/namespace", "value": "{jupyterhub}"}]'
      restartPolicy: OnFailure
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jupyterhub-admin
  namespace: jupyterhub
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jupyterhub-patch-role
  namespace: jupyterhub
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["rolebindings"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jupyterhub-patch-rolebinding
  namespace: jupyterhub
subjects:
- kind: ServiceAccount
  name: jupyterhub-admin
  namespace: jupyterhub
roleRef:
  kind: Role
  name: jupyterhub-patch-role
  apiGroup: rbac.authorization.k8s.io