apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

helmCharts:
- name: jupyterhub
  repo: https://hub.jupyter.org/helm-chart/
  version: 4.0.0
  releaseName: jupyterhub
  # valuesFile: prod-values.yaml
