apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

helmCharts:
  - name: analytics-workspace-management
    repo: https://lsc-sde.github.io/iac-helm-repository/
    version: 0.1.48 # Update to your desired version
    releaseName: analytics-workspace-management
    namespace: awms
