apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: xk8tre-tls
spec:
  secretName: xk8tre-tls
  privateKey:
    rotationPolicy: Always
  commonName: base-xk8tre.org
  dnsNames:
    - base-xk8tre.org
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer