apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: xk8tre-tls
  namespace: keycloak
spec:
  secretName: keycloak.base-xk8tre.org-tls
  privateKey:
    rotationPolicy: Always
  commonName: keycloak.base-xk8tre.org
  dnsNames:
    - keycloak.base-xk8tre.org
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
