apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/k8tre/k8tre.git
              revision: main
              directories:
                - path: agnostics/nginx/*/envs/*
          - clusters:
              selector:
                matchLabels:
                  environment: "{{index .path.segments 4}}"
                  vendor: "{{index .path.segments 2}}"
                matchExpressions:
                  - key: skip-nginx
                    operator: NotIn
                    values: ["true"]
  template:
    metadata:
      name: "{{index .path.segments 1}}-{{.nameNormalized}}"
      annotations:
        argocd.argoproj.io/instance: "{{index .path.segments 1}}-{{index .path.segments 4}}"
        argocd.argoproj.io/sync-wave: "-8" # Install after Cilium and Metallb
    spec:
      project: default
      source:
        repoURL: https://github.com/k8tre/k8tre.git
        targetRevision: main
        path: "{{.path.path}}"
      destination:
        server: "{{.server}}"
        namespace: ingress-nginx
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
